### ISSUE TITLE
5.4.2「入力画面を作ろう」の章で、作成後に画面確認が出来ない

### ISSUE THREAD

**Issue by NomuraShunsuke** [pco2699/NullSuck-AI#10]
@pco2699 
ぬるさくAIアプリ開発入門の上記タイトルの動作確認をしたいのですが、以下のエラーがでてしまい
動作確認のページ「ttp://localhost:3000/」を開いても入力画面が表示されません。
次の作業に進めるためにエラー解消をしたいのですが、原因を調べて頂くことは可能でしょうか。
原因に関連がありそうなページを見つけたため、添付しておきます。
https://github.com/nuxt-community/hackernews-nuxt-ts/issues/20
```
 ERROR  in ./pages/index.vue?vue&type=script&lang=ts&                                         friendly-errors 17:44:46

Module parse failed: Unexpected character '@' (17:0)                                          friendly-errors 17:44:46
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| // 使うことを宣言し、同時にimport
|
> @Component({
|   components: {
|     FormCard: () => import('../components/FormCard.vue')
                                                                                              friendly-errors 17:44:46
 @ ./pages/index.vue?vue&type=script&lang=ts& 1:0-117 1:133-136 1:138-252 1:138-252
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

**Comment by pco2699** [comment]
@NomuraShunsuke 
ありがとうございます。確認してみます。
（おそらくバージョン周りで動かなくなってると推測してます。）

**Comment by pco2699** [comment]
@NomuraShunsuke 
いただいたIssueと手元の環境をみる限り、やはりバージョンの整合性が原因と思われます。
（@nuxt/typescriptとnuxtのバージョンが合ってなさそう）

以下のこのGithubに含まれている package.json と yarn.lockファイルを現状のものをバックアップしたうえで、clientディレクトリにコピー、上書きしていただき、動くか確認をお願いしてもよいでしょうか？

https://github.com/pco2699/NullSuck-AI/blob/master/client/yarn.lock
https://github.com/pco2699/NullSuck-AI/blob/master/client/package.json

こちらをプロジェクトにコピーした後、以下の一連のコマンドを打って立ち上がるか確認してみてください
```
$ rm -rf node_modules
$ yarn
$ yarn run dev
```

**Comment by NomuraShunsuke** [comment]
@pco2699  直りました！ありがとうございます。
